# Generated by Django 3.2.3 on 2021-05-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_populate_rankings'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userranking',
            constraint=models.UniqueConstraint(fields=('user', 'rated_by'), name='unique_rating_per_user'),
        ),
    ]
