# Generated by Django 3.2.3 on 2021-07-15 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_userranking_unique_rating_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('LEAGUE', 'LEAGUE'), ('VALORANT', 'VALORANT')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='userranking',
            name='ranking_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rankings.rankingtype'),
        ),
    ]
