# Generated by Django 3.2.3 on 2021-07-16 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0003_auto_20210715_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorantRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('SENTINEL', 'SENTINEL'), ('INITIATOR', 'INITIATOR'), ('CONTROLLER', 'CONTROLLER'), ('DUELIST', 'DUELIST')], max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='userleaguerolepreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='league_role_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserValorantRolePreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='off_role_preferences', to='roles.valorantrole')),
                ('primary_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_preferences', to='roles.valorantrole')),
                ('secondary_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_preferences', to='roles.valorantrole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valorant_role_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
